/**
 * Builds the game's sound effects from Kenney's CC0 packs.
 *
 * The synthesised oscillator blips these replace were honest but thin — pure
 * tones with no body, which read as "prototype". These are recorded one-shots,
 * and the only assets in the project not generated by code: the licence is CC0,
 * so there is nothing to attribute, nothing to renew and nothing to revoke.
 *
 * The packs are not vendored — five megabytes of source for thirty kilobytes of
 * output is not worth a repository — so this script fetches them, and the eight
 * files it writes are committed. It is run by hand when the assets change, not
 * in CI: it needs ffmpeg and a network.
 *
 * The Android build has the same script and the same eight files. They are not
 * shared through `core/` because they are not part of the simulation: the two
 * builds could diverge here and neither leaderboard would notice.
 *
 *   node scripts/build-sfx.mjs
 *
 * Every cue is trimmed hard. A UI click that rings for 300 ms is a click you
 * hear underneath the next one, and `ignite` can fire every 9 ms on a dense
 * board, so its tail is cut to almost nothing — the rest of its weight comes
 * from the pitch rising with the combo, which reads as one sound, not eighty.
 */
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdirSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import { inflateRawSync } from 'node:zlib';
import { fileURLToPath } from 'node:url';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const OUT = fileURLToPath(new URL('../public/sfx', import.meta.url));
const WORK = join(tmpdir(), 'fuse-sfx');

/**
 * Kenney publishes each pack behind a donation prompt whose "continue without
 * donating" link is the real zip, with a cache-busting hash in the path.
 * Scraping that link survives the hash rolling; a hardcoded URL would not.
 */
const PACKS = {
  interface: 'interface-sounds',
  digital: 'digital-audio',
  scifi: 'sci-fi-sounds',
};

/**
 * The cue list.
 *
 * `trim` is where the sound is cut and `fade` how long it takes to get there.
 * The numbers are the shortest that still let each sound finish its attack,
 * chosen against how often that cue can fire.
 */
const CUES = [
  // Tray taps happen constantly. Anything with a tail becomes a rattle.
  { name: 'select', pack: 'interface', file: 'tick_002', trim: 0.06, fade: 0.01 },
  // A piece meeting the board: a bright pluck, like contact being made.
  { name: 'place', pack: 'interface', file: 'pluck_001', trim: 0.16, fade: 0.03 },
  // Taking it back is that gesture undone, so it answers lower and shorter.
  { name: 'pickup', pack: 'interface', file: 'back_003', trim: 0.09, fade: 0.02 },
  // "That does not fit" is information, not punishment — so this is the dullest,
  // quietest error in the pack on purpose. A harsh buzzer here would teach
  // players to stop experimenting, and experimenting is the game.
  { name: 'invalid', pack: 'interface', file: 'error_008', trim: 0.18, fade: 0.04 },
  // The charge before the run. The one cue allowed to take its time.
  { name: 'launch', pack: 'digital', file: 'phaserUp4', trim: 0.4, fade: 0.06 },
  // A node lighting: played up to a hundred times in a run and pitch-shifted by
  // the combo, so it has to be a ping and nothing else.
  { name: 'ignite', pack: 'interface', file: 'glass_005', trim: 0.09, fade: 0.02 },
  // A bomb eats the spark. Low and final, and allowed to be the loudest thing
  // in the game because it means the run just got worse.
  { name: 'bomb', pack: 'scifi', file: 'lowFrequency_explosion_001', trim: 0.7, fade: 0.12 },
  // The result screen. A chime, not a fanfare — it plays whether the run was
  // good or bad, and congratulating a bad one is worse than saying nothing.
  { name: 'result', pack: 'digital', file: 'threeTone2', trim: 0.75, fade: 0.12 },
];

/** Peak ceiling. Several sources decode above 0 dBFS, and AAC can overshoot a
 *  peak-limited signal by a few tenths on the way back out, so leave room. */
const CEILING_DB = -2;

function run(cmd, args) {
  return execFileSync(cmd, args, { maxBuffer: 1 << 28 });
}

/**
 * Reads a zip without shelling out.
 *
 * `tar` is on PATH on both Windows and CI but they are not the same tar: the
 * GNU build that ships with Git for Windows reads `C:\...` as a remote host and
 * tries to open an rsh connection. Forty lines of central-directory parsing is
 * less trouble than detecting which tar this is, and these archives are plain
 * stored-or-deflated entries with nothing exotic in them.
 */
function readZip(buf) {
  const eocd = buf.lastIndexOf(Buffer.from([0x50, 0x4b, 0x05, 0x06]));
  if (eocd < 0) throw new Error('not a zip');
  const count = buf.readUInt16LE(eocd + 10);
  let p = buf.readUInt32LE(eocd + 16);

  const entries = new Map();
  for (let i = 0; i < count; i++) {
    if (buf.readUInt32LE(p) !== 0x02014b50) throw new Error('bad central directory');
    const method = buf.readUInt16LE(p + 10);
    const size = buf.readUInt32LE(p + 20);
    const nameLen = buf.readUInt16LE(p + 28);
    const extraLen = buf.readUInt16LE(p + 30);
    const commentLen = buf.readUInt16LE(p + 32);
    const local = buf.readUInt32LE(p + 42);
    const name = buf.toString('utf8', p + 46, p + 46 + nameLen);
    entries.set(name, { method, size, local });
    p += 46 + nameLen + extraLen + commentLen;
  }

  return (name) => {
    const e = entries.get(name);
    if (!e) return null;
    // The local header repeats the name and extra fields, and its lengths are
    // the authoritative ones — the central directory's extra field is often a
    // different size.
    const nameLen = buf.readUInt16LE(e.local + 26);
    const extraLen = buf.readUInt16LE(e.local + 28);
    const start = e.local + 30 + nameLen + extraLen;
    const raw = buf.subarray(start, start + e.size);
    return e.method === 0 ? raw : inflateRawSync(raw);
  };
}

function fetchPack(key) {
  const slug = PACKS[key];
  const file = join(WORK, `${slug}.zip`);

  if (!existsSync(file)) {
    console.log(`fetching ${slug}...`);
    const page = run('curl', ['-sS', '--max-time', '60', `https://kenney.nl/assets/${slug}`]).toString();
    const zip = page.match(/https:\/\/kenney\.nl\/media\/pages\/assets\/[^'"]*\.zip/)?.[0];
    if (!zip) throw new Error(`no download link on the ${slug} page — did the layout change?`);
    mkdirSync(WORK, { recursive: true });
    run('curl', ['-sS', '-L', '--max-time', '300', '-o', file, zip]);
  }

  return readZip(readFileSync(file));
}

const packs = new Map();
function sourceFile(key, name) {
  if (!packs.has(key)) packs.set(key, fetchPack(key));
  const data = packs.get(key)(`Audio/${name}.ogg`);
  if (!data) throw new Error(`${name}.ogg is not in the ${PACKS[key]} pack`);
  // ffmpeg wants a path, and a temp file is cheaper than plumbing a pipe.
  const path = join(WORK, `${key}-${name}.ogg`);
  writeFileSync(path, data);
  return path;
}

/**
 * Loudest sample in the region that survives the trim, in dBFS.
 *
 * Measuring the whole file would let a tail we are about to cut decide the gain
 * of the part we keep — the bomb's two-second decay would hold the impact down
 * by several dB for no reason. ffmpeg reports this on stderr and still exits 0,
 * which execFileSync hides, so this one call goes through spawnSync.
 */
function trimmedPeak(input, trim) {
  const res = spawnSync(
    'ffmpeg',
    ['-hide_banner', '-i', input, '-af', `atrim=0:${trim},volumedetect`, '-f', 'null', '-'],
    { encoding: 'utf8', maxBuffer: 1 << 28 }
  );
  const db = Number(/max_volume:\s*(-?[\d.]+) dB/.exec(res.stderr ?? '')?.[1] ?? NaN);
  if (!Number.isFinite(db)) throw new Error(`could not read the level of ${input}`);
  return db;
}

mkdirSync(OUT, { recursive: true });

const built = [];
for (const cue of CUES) {
  const src = sourceFile(cue.pack, cue.file);
  const peak = trimmedPeak(src, cue.trim);
  const gain = (CEILING_DB - peak).toFixed(2);
  const fadeStart = Math.max(0, cue.trim - cue.fade).toFixed(3);
  const dest = join(OUT, `${cue.name}.m4a`);

  // AAC rather than Ogg or WebM: it is the one compressed format every target
  // decodes, including Safari and the Android WebView, and unlike MP3 it does
  // not prepend encoder delay — which on a 60 ms click is audible as lateness.
  run('ffmpeg', [
    '-hide_banner', '-v', 'error', '-y', '-i', src,
    '-af',
    `atrim=0:${cue.trim},asetpts=N/SR/TB,afade=t=out:st=${fadeStart}:d=${cue.fade},volume=${gain}dB`,
    '-ac', '1', '-ar', '44100', '-c:a', 'aac', '-b:a', '96k',
    dest,
  ]);

  const bytes = readFileSync(dest).length;
  built.push({ ...cue, peak, bytes });
  console.log(
    `${cue.name.padEnd(8)} ${cue.pack}/${cue.file}`.padEnd(44) +
      `${(cue.trim * 1000).toFixed(0).padStart(4)} ms  ${String(gain).padStart(7)} dB  ${String(bytes).padStart(5)} B`
  );
}

const total = built.reduce((n, b) => n + b.bytes, 0);
console.log(`\n${built.length} cues, ${(total / 1024).toFixed(1)} kB, written to public/sfx/`);
console.log('Source: Kenney (kenney.nl), CC0 1.0 — credited in docs/credits.md.');
